windows:
  - name: puppet
    root: ~/github/puppet
    layout: even-horizontal
    panes:
      - clear
      - clear
  - name: terminals
    root: ~/github
    layout: even-horizontal
    panes:
      - clear
      - clear
  - name: dotfiles
    root: ~/github/dotfiles
    layout: even-horizontal
    panes:
      - clear
      - clear
  - name: notes
    root: ~/github/notes
    layout: even-horizontal
    panes:
      - clear
      - clear
  - name: worklog
    root: ~/github/github-notes
    layout: even-horizontal
    panes:
      - clear
      - clear
